

MODEL_DIR = 'app/models/'
IMAGE_GENDER_MODEL_PATH = MODEL_DIR + 'Res18_gender.pt'
IMAGE_AGE_MODEL_PATH = MODEL_DIR + 'Res18_age.pt'
IMAGE_RACE_MODEL_PATH = MODEL_DIR + 'Res18_race.pt'
NAME_GENDER_MODEL_PATH = MODEL_DIR + 'name_gen.pt'
NAME_GENDER_DICT_PATH = MODEL_DIR + 'namedict_us.json'

IMAGE_GENDER_MODEL_URL = ""
IMAGE_AGE_MODEL_URL = ""
IMAGE_RACE_MODEL_URL = ""
NAME_GENDER_MODEL_URL = ""
NAME_GENDER_DICT_URL = ""

INFERENCE_ON_CPU = True

PORT = 8080



